"use client";
import { useMemo, useRef, useState } from "react";
import { Menu, X, ArrowDownLeft, ArrowUpRight, BarChart3, ChevronRight, Loader2, ShieldCheck, Sparkles, TrendingUp, Upload, Wallet, Landmark, Activity, FileText, CalendarDays, Users, Store, Repeat2 } from "lucide-react";
import * as pdfjsLib from "pdfjs-dist/legacy/build/pdf.mjs";
import { buildFinancialAnalytics, type AnalyticsTransaction, monthLabel } from "../../lib/financialAnalytics";
import { parsePalmPayTransactions } from "../../lib/palmpayParser";
import "./analytics.css";
pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/5.4.54/pdf.worker.min.mjs";
const money=(n:number)=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:2}).format(n);
const internal=/OWealth (Withdrawal|Balance)|Auto-save to OWealth|VAT on Transfer Fee|Stamp Duty|OWealth Interest Earned/i;
const dateStart=/\b(\d{1,2}\s+(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s+\d{4})\s+(\d{1,2}:\d{2}(?::\d{2})?)\b/gi;
const amount=/\b(?:₦\s*)?\d{1,3}(?:,\d{3})*(?:\.\d{2})\b|\b(?:₦\s*)?\d+(?:\.\d{2})\b/g;
const clean=(s:string)=>s.replace(/\s+/g," ").trim();const toAmount=(s:string)=>Number(s.replace(/[₦,\s]/g,""));
function parseOpayTransactions(text:string):AnalyticsTransaction[]{const normalized=text.replace(/[\u00a0\u2007\u202f]/g," ").replace(/[|]/g," | ").replace(/\s+/g," ").trim();const starts=[...normalized.matchAll(dateStart)],out:AnalyticsTransaction[]=[];for(let i=0;i<starts.length;i++){const block=normalized.slice(starts[i].index!,i+1<starts.length?starts[i+1].index:normalized.length).trim();if(internal.test(block))continue;const head=block.match(dateStart);if(!head)continue;const hm=head[0].match(/^(\d{1,2}\s+(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s+\d{4})\s+(\d{1,2}:\d{2}(?::\d{2})?)/i);if(!hm)continue;const incoming=/\bTransfer\s+from\s+(.+?)(?=\s+(?:\||--|₦?\d[\d,]*(?:\.\d{2})?)|$)/i.exec(block),outgoing=/\bTransfer\s+to\s+(.+?)(?=\s+(?:\||--|₦?\d[\d,]*(?:\.\d{2})?)|$)/i.exec(block),direction=outgoing?"sent":incoming?"received":null;if(!direction)continue;const match=direction==="sent"?outgoing!:incoming!,party=clean(match[1]).replace(/\s*\|.*$/," ").replace(/\s+(?:Narration|Reference|Remark|Amount|Balance|Transfer|Credit|Debit)\b.*$/i,"").trim()||"Unknown",tail=block.slice((match.index??0)+match[0].length),nums=[...tail.matchAll(amount)].map(m=>toAmount(m[0])).filter(n=>Number.isFinite(n)&&n>0),after=tail.match(/--\s*(?:₦\s*)?([\d,]+(?:\.\d{2})?)/),before=tail.match(/(?:₦\s*)?([\d,]+(?:\.\d{2})?)\s*--/);let chosen:number|undefined;if(direction==="received"&&after)chosen=toAmount(after[1]);if(direction==="sent"&&before)chosen=toAmount(before[1]);if(chosen===undefined)chosen=nums[0];if(chosen)out.push({date:hm[1],time:hm[2],description:clean(block),amount:chosen,party,direction});}return [...new Map(out.map(t=>[`${t.date}|${t.time}|${t.direction}|${t.party}|${t.amount}`,t])).values()];}
async function extract(file:File){const pdf=await pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;let text="";for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p),c=await page.getTextContent(),items=c.items as Array<{str?:string;transform?:number[]}>;let current="",lastY:number|undefined;const lines:string[]=[];for(const item of items){const value=typeof item?.str==="string"?item.str:"",y=item.transform?.[5];if(!value)continue;if(lastY!==undefined&&y!==undefined&&Math.abs(y-lastY)>3){if(current)lines.push(current);current=""}current+=` ${value}`;lastY=y;}if(current)lines.push(current);text+=lines.join("\n")+"\n";}return text;}
const tabs=["Overview","Monthly","Income","People","Expenses","Categories","Merchants","Recurring"] as const;type Tab=typeof tabs[number];type Bank="OPay"|"PalmPay";const navIcon:Record<Tab,React.ReactNode>={Overview:<Activity/>,Monthly:<CalendarDays/>,Income:<ArrowDownLeft/>,People:<Users/>,Expenses:<ArrowUpRight/>,Categories:<BarChart3/>,Merchants:<Store/>,Recurring:<Repeat2/>};
export default function Advanced(){const input=useRef<HTMLInputElement>(null);const[tx,setTx]=useState<AnalyticsTransaction[]>([]);const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[tab,setTab]=useState<Tab>("Overview");const[menu,setMenu]=useState(false);const[selected,setSelected]=useState<any>(null);const[bank,setBank]=useState("Unknown bank");const[selectedBank,setSelectedBank]=useState<Bank|null>(null);const analytics=useMemo(()=>buildFinancialAnalytics(tx),[tx]);
async function upload(file?:File){if(!file)return;if(!selectedBank){setError("Select OPay or PalmPay before uploading your statement.");return;}setError("");setLoading(true);try{if(file.type!=="application/pdf")throw Error("PDF statements only.");const text=await extract(file);const rows=selectedBank==="PalmPay"?parsePalmPayTransactions(text):parseOpayTransactions(text);if(!rows.length)throw Error(`No supported ${selectedBank} transaction rows were detected.`);setBank(selectedBank);setTx(rows);}catch(e:any){setError(e.message||"Could not analyze statement.");}finally{setLoading(false)}}
const choose=(t:Tab)=>{setTab(t);setMenu(false)};
if(!tx.length)return <main><header className="aiHeader"><div className="aiBrand"><span>S</span><strong>Statemently</strong></div><div className="aiSecure"><ShieldCheck size={15}/> Local & private</div></header><section className="aiHero"><div className="aiEyebrow"><Sparkles size={14}/> Bank statement intelligence</div><h1>See your money<br/><em>with clarity.</em></h1><p>Turn a bank statement into a clear, beautiful view of your money flow — income, expenses, people, merchants and patterns.</p><div style={{marginBottom:18}}><div style={{fontWeight:700,fontSize:14,marginBottom:10}}>Select your bank</div><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:10}}>{(["OPay","PalmPay"] as Bank[]).map(b=><button key={b} type="button" onClick={()=>{setSelectedBank(b);setError("")}} aria-pressed={selectedBank===b} style={{padding:"14px 16px",borderRadius:14,border:selectedBank===b?"2px solid currentColor":"1px solid rgba(127,127,127,.28)",background:selectedBank===b?"rgba(127,127,127,.12)":"transparent",color:"inherit",fontWeight:700,cursor:"pointer",textAlign:"left"}}><Landmark size={17} style={{verticalAlign:"middle",marginRight:8}}/>{b}<div style={{fontSize:11,fontWeight:500,opacity:.65,marginTop:5}}>{b==="OPay"?"Existing OPay parser":"PalmPay PDF parser"}</div></button>)}</div></div><button className="aiUpload" disabled={!selectedBank||loading} onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();upload(e.dataTransfer.files?.[0])}}><div className="aiUploadIcon">{loading?<Loader2 className="spin"/>:<Upload/>}</div><div><b>{loading?"Analyzing statement…":selectedBank?`Upload ${selectedBank} statement`:"Select a bank to continue"}</b><span>{loading?"Parsing transactions locally":"PDF only · processed in your browser"}</span></div><ChevronRight className="aiArrow"/></button><input ref={input} hidden type="file" accept="application/pdf" onChange={e=>upload(e.target.files?.[0])}/>{error&&<div className="aiError">{error}</div>}<div className="aiFeatures"><span>Financial overview</span><span>Monthly analysis</span><span>People</span><span>Categories</span><span>Recurring</span></div></section></main>;
const o=analytics.overview,max=Math.max(1,...analytics.monthly.flatMap(m=>[m.received,m.sent]));return <main><header className="aiHeader"><div className="aiBrand"><span>S</span><strong>Statemently</strong></div><div className="aiHeaderRight"><div className="aiSecure"><ShieldCheck size={15}/> {tx.length} transactions</div><button className="aiMenuButton" aria-label="Open menu" onClick={()=>setMenu(v=>!v)}>{menu?<X/>:<Menu/>}</button></div>{menu&&<div className="aiMenu"><div className="aiMenuTitle">Financial analysis</div>{tabs.map(t=><button className={tab===t?"active":""} onClick={()=>choose(t)} key={t}><span className="aiMenuItemIcon">{navIcon[t]}</span><span className="aiMenuItemLabel">{t}</span><ChevronRight size={15}/></button>)}<div className="aiMenuDivider"/><button onClick={()=>{setTx([]);setSelectedBank(null);setBank("Unknown bank");setMenu(false)}}>Analyze another statement</button></div>}</header><section className="aiDashboard"><div className="aiTitle"><div><div className="aiEyebrow">Financial intelligence</div><h2>Your money story</h2><p>Every insight calculated from your statement, locally.</p></div></div><div className="aiCurrent"><span>{tab}</span><button onClick={()=>setMenu(true)}><Menu size={15}/> Explore analysis</button></div>
{tab==="Overview"&&<><div className="aiStats"><Card icon={<Landmark/>} label="Bank" value={bank} cls="blue"/><Card icon={<ArrowDownLeft/>} label="Received" value={money(o.totalReceived)} cls="green"/><Card icon={<ArrowUpRight/>} label="Spent" value={money(o.totalSpent)} cls="red"/><Card icon={<TrendingUp/>} label="Net cash flow" value={money(o.netCashFlow)} cls="blue"/><Card icon={<Wallet/>} label="Transactions" value={String(o.totalTransactions)} cls="purple"/></div><div className="aiBalance"><Mini label="Opening balance" value={o.openingBalance==null?"—":money(o.openingBalance)}/><Mini label="Closing balance" value={o.closingBalance==null?"—":money(o.closingBalance)}/><Mini label="Highest balance" value={o.highestBalance==null?"—":money(o.highestBalance)}/><Mini label="Lowest balance" value={o.lowestBalance==null?"—":money(o.lowestBalance)}/></div><section className="aiPanel"><Head title="Monthly cash flow" sub="Income vs expenses"/><div className="aiChart">{analytics.monthly.map(m=><div className="aiMonth" key={m.key}><div className="aiBars"><i style={{height:`${Math.max(6,m.received/max*100)}%`}}/><i style={{height:`${Math.max(6,m.sent/max*100)}%`}}/></div><b>{monthLabel(m.key)}</b><small>{money(m.net)}</small></div>)}</div><div className="aiLegend"><span><i/> Income</span><span><i/> Expenses</span></div></section></>}
{tab==="Monthly"&&<section className="aiGrid">{analytics.monthly.map(m=><article className="aiMonthCard" key={m.key}><span>{m.label}</span><h3>{money(m.net)}</h3><p>Net cash flow</p><div><Metric label="Received" value={money(m.received)}/><Metric label="Spent" value={money(m.sent)}/><Metric label="Incoming" value={String(m.incomingCount)}/><Metric label="Outgoing" value={String(m.outgoingCount)}/><Metric label="Senders" value={String(m.uniqueSenders)}/><Metric label="Recipients" value={String(m.uniqueRecipients)}/></div></article>)}</section>}
{tab==="Income"&&<><div className="aiStats"><Card icon={<ArrowDownLeft/>} label="Total income" value={money(analytics.income.totalIncome)} cls="green"/><Card icon={<BarChart3/>} label="Largest incoming" value={money(analytics.income.largestIncoming)} cls="blue"/><Card icon={<TrendingUp/>} label="Average incoming" value={money(analytics.income.averageIncoming)} cls="purple"/><Card icon={<Wallet/>} label="Incoming count" value={String(analytics.income.incomingTransactions)} cls="green"/></div><List title="Top income sources" rows={analytics.income.topSources} value="totalReceived" select={setSelected}/></>}
{tab==="People"&&<><List title="Who sent money" sub="People and accounts that sent money into this account" rows={analytics.parties.filter((r:any)=>r.totalReceived>0)} value="totalReceived" select={setSelected}/><List title="Who received money" sub="People and accounts this account sent money to" rows={analytics.parties.filter((r:any)=>r.totalSent>0)} value="totalSent" select={setSelected}/></>}
{tab==="Expenses"&&<List title="Top recipients" rows={analytics.expenses.topRecipients} value="totalSent" select={setSelected}/>} 
{tab==="Categories"&&<section className="aiPanel"><Head title="Spending categories" sub="Detected from transaction descriptions"/><p className="aiNotice">Categories are analytical classifications, not bank-provided labels.</p>{analytics.categories.map(c=><div className="cat" key={c.category}><div><b>{c.category}</b><span>{c.count} transactions · {c.percentage.toFixed(1)}%</span></div><strong>{money(c.amount)}</strong><div className="catBar"><i style={{width:`${c.percentage}%`}}/></div></div>)}</section>}
{tab==="Merchants"&&<List title="Top merchants" rows={analytics.merchants} value="totalSpent" merchant/>}
{tab==="Recurring"&&<section className="aiPanel"><Head title="Detected recurring transactions" sub="Repeated timing and descriptions"/><p className="aiNotice">These are detected patterns, not guarantees of future payments.</p>{analytics.recurring.length?analytics.recurring.map((r,i)=><div className="aiRecurring" key={i}><div className="aiRound">↻</div><div><b>{r.description}</b><span>{r.frequency} · {r.occurrences} occurrences · {r.firstOccurrence} → {r.mostRecentOccurrence}</span></div><strong>{money(r.averageAmount)}</strong><small>{Math.round(r.confidence*100)}% confidence</small></div>):<div className="aiEmpty">No recurring pattern detected.</div>}</section>}
{selected&&<div className="aiModal" onClick={()=>setSelected(null)}><div className="aiModalCard" onClick={e=>e.stopPropagation()}><button onClick={()=>setSelected(null)}>×</button><div className="aiAvatar">{selected.name.slice(0,1).toUpperCase()}</div><h3>{selected.name}</h3><p>{selected.receivedCount} received · {selected.sentCount} sent · {selected.months.length} active months</p><div className="aiProfile"><Mini label="Received" value={money(selected.totalReceived)}/><Mini label="Sent" value={money(selected.totalSent)}/><Mini label="Largest received" value={money(selected.largestReceived)}/><Mini label="Largest sent" value={money(selected.largestSent)}/></div><div className="aiTransactions">{selected.transactions.slice(-10).reverse().map((t:any,i:number)=><div key={i}><span>{t.date}</span><b>{t.party}</b><strong className={t.direction}>{t.direction==="received"?"+":"−"}{money(t.amount)}</strong></div>)}</div></div></div>}
<div className="aiPrivacy"><ShieldCheck size={18}/><div><b>Private by design</b><span>PDF parsing and analytics run in your browser. No statement upload is required.</span></div></div></section></main>}
function Card({icon,label,value,cls}:{icon:React.ReactNode;label:string;value:string;cls:string}){return <article className="aiCard"><div className={`aiIcon ${cls}`}>{icon}</div><span>{label}</span><strong title={value}>{value}</strong></article>}
function Mini({label,value}:{label:string;value:string}){return <div className="aiMini"><span>{label}</span><strong>{value}</strong></div>}
function Metric({label,value}:{label:string;value:string}){return <div><span>{label}</span><b>{value}</b></div>}
function Head({title,sub}:{title:string;sub:string}){return <div className="aiHead"><div><h3>{title}</h3><p>{sub}</p></div></div>}
function List({title,sub,rows,value,select,merchant=false}:{title:string;sub?:string;rows:any[];value:string;select?:(x:any)=>void;merchant?:boolean}){return <section className="aiPanel"><Head title={title} sub={sub|| (merchant?"Grouped merchant activity":"Tap a row for a detailed profile")}/><div className="aiList">{rows.slice(0,30).map((r:any)=><button key={r.name||r.merchant} onClick={()=>select?.(r)}><div className="aiAvatar">{(r.name||r.merchant).slice(0,1).toUpperCase()}</div><div><b>{r.name||r.merchant}</b><span>{merchant?`${r.count} transactions · avg ${money(r.averageTransaction)}`:`${r.receivedCount||0} received · ${r.sentCount||0} sent · ${r.months?.length||0} active months`}</span></div><strong>{money(r[value]||0)}</strong><ChevronRight size={15}/></button>)}</div></section>}
